### ISSUE TITLE
音楽を停止できるようにする

### ISSUE THREAD

**Issue by SIY1121** [cojt-12th-music/create-music-web#38]
なぜ今まで忘れていた

**Comment by nbz16** [comment]
音楽が再生中かどうかの情報(isPlaying的なやつ)ってstoreに持たせるんだっけ？
それともPlayer.vueに持たせる？
@SIY1121 @shikibu9419

**Comment by SIY1121** [comment]
今はどこにも持ってないんだけど、ストアに持たせたいって思ってて、Playerの改修がてら自分が整備しようと思ってた。
とりあえず再生状態については関知しないで、`stop()` 呼ばれたら音を止める実装を先にやってもらえると 🙏 

いまは`Instrument.vue` の`demoMelody()` （この名前おかしいから変えてほしい）を呼び出すと一気にスケジューリングしてるんだけど、このままだとキャンセルできないから、各Instrumentのdataにスケジューリングしたnodesを保持しておいて、途中で`stop()` が呼び出されたら保持しておいたnodeを全部stopしてdisconnectする感じで組むといいかも？
